// flow-typed signature: 95a91f53f5673603d59480fcd9c226fe
// flow-typed version: <<STUB>>/critters-webpack-plugin_v^1.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'critters-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'critters-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'critters-webpack-plugin/dist/critters' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/src/css' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/src/dom' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/src/util' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/test/_helpers' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/test/fixtures/basic/index' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/test/fixtures/external/index' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/test/fixtures/raw/index' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/test/fixtures/unused/index' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/test/index.test' {
  declare module.exports: any;
}

declare module 'critters-webpack-plugin/test/standalone.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'critters-webpack-plugin/dist/critters.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/dist/critters'>;
}
declare module 'critters-webpack-plugin/src/css.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/src/css'>;
}
declare module 'critters-webpack-plugin/src/dom.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/src/dom'>;
}
declare module 'critters-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/src/index'>;
}
declare module 'critters-webpack-plugin/src/util.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/src/util'>;
}
declare module 'critters-webpack-plugin/test/_helpers.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/test/_helpers'>;
}
declare module 'critters-webpack-plugin/test/fixtures/basic/index.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/test/fixtures/basic/index'>;
}
declare module 'critters-webpack-plugin/test/fixtures/external/index.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/test/fixtures/external/index'>;
}
declare module 'critters-webpack-plugin/test/fixtures/raw/index.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/test/fixtures/raw/index'>;
}
declare module 'critters-webpack-plugin/test/fixtures/unused/index.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/test/fixtures/unused/index'>;
}
declare module 'critters-webpack-plugin/test/index.test.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/test/index.test'>;
}
declare module 'critters-webpack-plugin/test/standalone.test.js' {
  declare module.exports: $Exports<'critters-webpack-plugin/test/standalone.test'>;
}
