// flow-typed signature: ae4bedbb75d7d7613df99d3113e9ec6e
// flow-typed version: <<STUB>>/docz-plugin-css_v^0.11.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docz-plugin-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docz-plugin-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docz-plugin-css/dist/index' {
  declare module.exports: any;
}

declare module 'docz-plugin-css/dist/index.m' {
  declare module.exports: any;
}

declare module 'docz-plugin-css/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docz-plugin-css/dist/index.js' {
  declare module.exports: $Exports<'docz-plugin-css/dist/index'>;
}
declare module 'docz-plugin-css/dist/index.m.js' {
  declare module.exports: $Exports<'docz-plugin-css/dist/index.m'>;
}
declare module 'docz-plugin-css/dist/index.umd.js' {
  declare module.exports: $Exports<'docz-plugin-css/dist/index.umd'>;
}
