// flow-typed signature: a7d5fa06803689c360c0972244a3676f
// flow-typed version: <<STUB>>/docz_v^0.11.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docz/bin/index' {
  declare module.exports: any;
}

declare module 'docz/dist/index' {
  declare module.exports: any;
}

declare module 'docz/dist/index.m' {
  declare module.exports: any;
}

declare module 'docz/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docz/bin/index.js' {
  declare module.exports: $Exports<'docz/bin/index'>;
}
declare module 'docz/dist/index.js' {
  declare module.exports: $Exports<'docz/dist/index'>;
}
declare module 'docz/dist/index.m.js' {
  declare module.exports: $Exports<'docz/dist/index.m'>;
}
declare module 'docz/dist/index.umd.js' {
  declare module.exports: $Exports<'docz/dist/index.umd'>;
}
