// flow-typed signature: f571a54a737312d48507b6da7360509b
// flow-typed version: <<STUB>>/html-critical-webpack-plugin_v^2.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-critical-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-critical-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-critical-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-critical-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'html-critical-webpack-plugin/src/index'>;
}
