// flow-typed signature: 0794a5424a7a7cc7d7d491947892d4c0
// flow-typed version: <<STUB>>/postcss-utilities_v^0.8.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-utilities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-utilities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-utilities/lib/aspect-ratio' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/border-bottom-radius' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/border-color' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/border-left-radius' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/border-right-radius' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/border-style' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/border-top-radius' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/border-width' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/center-block' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/center' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/circle' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/clearfix-ie8' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/clearfix' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/collapse-directionals' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/directional-values' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/hd-breakpoint' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/helpers' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/hide-visually' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/horizontal-rule' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/margin' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/no-hover' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/no-js' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/padding' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/position' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/reset-list' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/reset-text' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/size' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/sticky-footer' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/text-hide' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/text-stroke' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/triangle' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/truncate-multiline' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/truncate' {
  declare module.exports: any;
}

declare module 'postcss-utilities/lib/word-wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-utilities/index' {
  declare module.exports: $Exports<'postcss-utilities'>;
}
declare module 'postcss-utilities/index.js' {
  declare module.exports: $Exports<'postcss-utilities'>;
}
declare module 'postcss-utilities/lib/aspect-ratio.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/aspect-ratio'>;
}
declare module 'postcss-utilities/lib/border-bottom-radius.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/border-bottom-radius'>;
}
declare module 'postcss-utilities/lib/border-color.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/border-color'>;
}
declare module 'postcss-utilities/lib/border-left-radius.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/border-left-radius'>;
}
declare module 'postcss-utilities/lib/border-right-radius.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/border-right-radius'>;
}
declare module 'postcss-utilities/lib/border-style.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/border-style'>;
}
declare module 'postcss-utilities/lib/border-top-radius.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/border-top-radius'>;
}
declare module 'postcss-utilities/lib/border-width.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/border-width'>;
}
declare module 'postcss-utilities/lib/center-block.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/center-block'>;
}
declare module 'postcss-utilities/lib/center.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/center'>;
}
declare module 'postcss-utilities/lib/circle.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/circle'>;
}
declare module 'postcss-utilities/lib/clearfix-ie8.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/clearfix-ie8'>;
}
declare module 'postcss-utilities/lib/clearfix.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/clearfix'>;
}
declare module 'postcss-utilities/lib/collapse-directionals.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/collapse-directionals'>;
}
declare module 'postcss-utilities/lib/directional-values.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/directional-values'>;
}
declare module 'postcss-utilities/lib/hd-breakpoint.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/hd-breakpoint'>;
}
declare module 'postcss-utilities/lib/helpers.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/helpers'>;
}
declare module 'postcss-utilities/lib/hide-visually.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/hide-visually'>;
}
declare module 'postcss-utilities/lib/horizontal-rule.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/horizontal-rule'>;
}
declare module 'postcss-utilities/lib/margin.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/margin'>;
}
declare module 'postcss-utilities/lib/no-hover.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/no-hover'>;
}
declare module 'postcss-utilities/lib/no-js.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/no-js'>;
}
declare module 'postcss-utilities/lib/padding.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/padding'>;
}
declare module 'postcss-utilities/lib/position.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/position'>;
}
declare module 'postcss-utilities/lib/reset-list.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/reset-list'>;
}
declare module 'postcss-utilities/lib/reset-text.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/reset-text'>;
}
declare module 'postcss-utilities/lib/size.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/size'>;
}
declare module 'postcss-utilities/lib/sticky-footer.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/sticky-footer'>;
}
declare module 'postcss-utilities/lib/text-hide.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/text-hide'>;
}
declare module 'postcss-utilities/lib/text-stroke.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/text-stroke'>;
}
declare module 'postcss-utilities/lib/triangle.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/triangle'>;
}
declare module 'postcss-utilities/lib/truncate-multiline.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/truncate-multiline'>;
}
declare module 'postcss-utilities/lib/truncate.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/truncate'>;
}
declare module 'postcss-utilities/lib/word-wrap.js' {
  declare module.exports: $Exports<'postcss-utilities/lib/word-wrap'>;
}
