// flow-typed signature: 0cd9eb5834cca089196a6446cd4d1ed8
// flow-typed version: <<STUB>>/prerender-spa-plugin_v^3.4.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prerender-spa-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prerender-spa-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prerender-spa-plugin/es5-autogenerated/index' {
  declare module.exports: any;
}

declare module 'prerender-spa-plugin/es6/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prerender-spa-plugin/es5-autogenerated/index.js' {
  declare module.exports: $Exports<'prerender-spa-plugin/es5-autogenerated/index'>;
}
declare module 'prerender-spa-plugin/es6/index.js' {
  declare module.exports: $Exports<'prerender-spa-plugin/es6/index'>;
}
declare module 'prerender-spa-plugin/index' {
  declare module.exports: $Exports<'prerender-spa-plugin'>;
}
declare module 'prerender-spa-plugin/index.js' {
  declare module.exports: $Exports<'prerender-spa-plugin'>;
}
